steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/macroleia:$BUILD_ID
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/macroleia:$BUILD_ID
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - macroleia
      - --image
      - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/macroleia:$BUILD_ID
      - --region
      - $_REGION
      - --platform
      - managed
      - --allow-unauthenticated
      - --min-instances
      - "0"
      - --set-env-vars
      - MACROLEIA_STORAGE=firestore
substitutions:
  _REGION: us-central1
  _REPOSITORY: cloud-run-source-deploy
images:
  - $_REGION-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY/macroleia:$BUILD_ID
